### ISSUE TITLE
"agrest-cayenne": '+' sign in include doesn't work

### ISSUE THREAD

**Issue by MProtasevich** [agrestio/agrest#438] opened 2020-02-27 09:28 UTC
Since global refactoring in 3.1 version, '+' sign in `include` query parameter doesn't work

Previously, by specifying it for any relation field, it was possible to join related tables with "LEFT JOIN" instead of "INNER JOIN" in conjunction with cayenne

**Comment by andrus** [comment] 2020-02-27 12:08
Looks like we only have tests for OUTER join in "cayenneExp" key. Didn't even know we supported that in in "include" :) Will need to investigate.

**Comment by andrus** [comment] 2020-03-01 14:48
At a closer look this should not be an issue. All includes are "OUTER" by definition (i.e. if there's no related object, the root object will still be present in the result). So "+" is meaningless in the context of an include.

If there an example of the opposite, please post the specifics and we'll investigate.

**Comment by MProtasevich** [comment] 2020-03-09 10:25
As far as I see, all the includes which refers to another entity results in generating just "JOIN" in SQL-statement via Cayenne, which by default is an INNER JOIN (for MySQL at least).

For instance we have tables `author` and `book` and we add "include=author.book" on AgRest side. The result SQL statement^ generated with Cayenne, would satisfy this template (for simplicity I used O2M-relation)
```sql
SELECT * FROM author AS a
  JOIN book AS b ON a.id = b.author_id
WHERE [statement parsed from cayenneExp]
```
Both Cayenne entities have the references to each other's DTOs.

And here author without any published book yet, won't be listed in results.

**Comment by andrus** [comment] 2020-03-09 11:00
I suspect the join is not caused by include, but rather by cayenneExp (where you can control it with + sign).

**Comment by MProtasevich** [comment] 2020-03-09 13:34
The '+' sign doesn't work within cayenneExp neither. I've checked `IncludeMerger:73` where paths from include are used to fetch `AgRelationship` and it seems that this '+' sign is not recognized as a service symbol in AgRest

**Comment by MProtasevich** [comment] 2020-03-10 08:18
Here is an example
We have `a` (root entity), `b`, `c` and `d` tables

```
include = "b.c_m.d_m"
include = {
  "cayenneExp": {
    "exp":"(c_field=\"c value\") or (d_m.d_field=\"d value\")"},
    "path":"b.c_m"
}
```
(postfix '_m' means "to-Many" relation)

And previously (AgRest version 3.0 and earlier LinkRest implementations) response was like this:
```json
{
  "success": true,
  "data": [
    {
      "id": 1,
      "b": {
        "id": 4,
        "c_m": [
          {
            "d_m": [],
            "c_field": "c value"
          },
          {
            "d_m": [
              {
                "id": 7,
                "d_field": "d value"
              }
            ],
            "c_field": "c value"
          }
        ]
      }
    }
  ],
  "total": 1
}
```

But after upgrade to AgRest 3.3 response looks like this (one element is missing in `c_m` collection):
```json
{
  "success": true,
  "data": [
    {
      "id": 1,
      "b": {
        "id": 4,
        "c_m": [
          {
            "d_m": [
              {
                "id": 7,
                "d_field": "d value"
              }
            ],
            "c_field": "c value"
          }
        ]
      }
    }
  ],
  "total": 1
}
```

**Comment by andrus** [comment] 2020-04-03 10:42
I just created a unit test with a similar model. Everything seems to work fine.

https://github.com/agrestio/agrest/commit/003e57d43a2cdaed23020f55683880a9485915c7

**Comment by andrus** [comment] 2020-04-14 14:47
Closing for now. If we find more evidence that this is broken, let's reopen.

**Closed by andrus** 2020-04-14 14:47 UTC
